#!/bin/bash
sudo passwd -l root
sudo passwd -l daemon
sudo passwd -l bin
sudo passwd -l sys
sudo passwd -l sync
sudo passwd -l games
sudo passwd -l man
sudo passwd -l lp
sudo passwd -l mail
sudo passwd -l news
sudo passwd -l uucp
sudo passwd -l proxy
sudo passwd -l www-data
sudo passwd -l backup
sudo passwd -l list
sudo passwd -l irc
sudo passwd -l gnats
sudo passwd -l nobody
sudo passwd -l libuuid
sudo passwd -l syslog
sudo passwd -l messagebus
sudo passwd -l usbmux
sudo passwd -l dnsmasq
sudo passwd -l avahi-autoipd
sudo passwd -l kernoops
sudo passwd -l rtkit
sudo passwd -l saned
sudo passwd -l whoopsie
sudo passwd -l avahi
sudo passwd -l lightdm
sudo passwd -l colord
sudo passwd -l hplip
sudo passwd -l pulse

