mkdir -p backup/etc
mkdir -p backup/etc/fail2ban
mkdir -p backup/etc/fail2ban/filter.d
mkdir -p backup/etc/modprobe.d
mkdir -p backup/etc/audisp
mkdir -p backup/etc/audisp/plugins.d
mkdir -p backup/etc/bluetooth
mkdir -p backup/etc/mysql
mkdir -p backup/etc/mysql/mysql.conf.d
mkdir -p backup/etc/init
mkdir -p backup/etc/init.d
mkdir -p backup/etc/pam.d
mkdir -p backup/etc/ssl
mkdir -p backup/etc/ssl/certs
mkdir -p backup/etc/audit
mkdir -p backup/etc/default
mkdir -p backup/etc/skel
mkdir -p backup/etc/apache2
mkdir -p backup/etc/apache2/mods-enabled
mkdir -p backup/etc/apache2/conf-enabled
mkdir -p backup/etc/apache2/sites-enabled
mkdir -p backup/etc/ssh
mkdir -p backup/etc/security
mkdir -p backup/etc/modsecurity
mkdir -p backup/etc/ufw
mkdir -p backup/etc/samba
mkdir -p backup/etc/php
mkdir -p backup/etc/php/7.2
mkdir -p backup/etc/php/7.2/fpm
mkdir -p backup/etc/php/7.2/apache2
mkdir -p backup/etc/php/7.2/cli
mkdir -p backup/etc/udev
mkdir -p backup/etc/udev/rules.d
mkdir -p backup/boot
mkdir -p backup/boot/grub
mkdir -p backup/lib
mkdir -p backup/lib/lsb
mkdir -p backup/usr
mkdir -p backup/usr/share
mkdir -p backup/usr/share/lightdm
mkdir -p backup/usr/share/lightdm/lightdm.conf.d

cp /etc/fail2ban/filter.d/http-get-dos.conf				  backup/etc/fail2ban/filter.d/http-get-dos.conf		
cp /etc/fail2ban/jail.local                                               backup/etc/fail2ban/jail.local
cp /etc/modprobe.d/hfsplus.conf                                           backup/etc/modprobe.d/hfsplus.conf
cp /etc/modprobe.d/cramfs.conf                                            backup/etc/modprobe.d/cramfs.conf
cp /etc/modprobe.d/dccp_ipv6.conf                                         backup/etc/modprobe.d/dccp_ipv6.conf
cp /etc/modprobe.d/sctp.conf                                              backup/etc/modprobe.d/sctp.conf
cp /etc/modprobe.d/blacklist.conf                                         backup/etc/modprobe.d/blacklist.conf
cp /etc/modprobe.d/vfat.conf                                              backup/etc/modprobe.d/vfat.conf
cp /etc/modprobe.d/jffs2.conf                                             backup/etc/modprobe.d/jffs2.conf
cp /etc/modprobe.d/hfs.conf                                               backup/etc/modprobe.d/hfs.conf
cp /etc/modprobe.d/appletalk.conf                                         backup/etc/modprobe.d/appletalk.conf
cp /etc/modprobe.d/usb-storage.conf                                       backup/etc/modprobe.d/usb-storage.conf
cp /etc/modprobe.d/net-pf-31.conf                                         backup/etc/modprobe.d/net-pf-31.conf
cp /etc/modprobe.d/dccp.conf                                              backup/etc/modprobe.d/dccp.conf
cp /etc/modprobe.d/bluetooth.conf                                         backup/etc/modprobe.d/bluetooth.conf
cp /etc/modprobe.d/dccp_ipv4.conf                                         backup/etc/modprobe.d/dccp_ipv4.conf
cp /etc/modprobe.d/freevxfs.conf                                          backup/etc/modprobe.d/freevxfs.conf
cp /etc/modprobe.d/udf.conf                                               backup/etc/modprobe.d/udf.conf
cp /etc/modprobe.d/squashfs.conf                                          backup/etc/modprobe.d/squashfs.conf
cp /etc/modprobe.d/rds.conf                                               backup/etc/modprobe.d/rds.conf
cp /etc/modprobe.d/tipc.conf                                              backup/etc/modprobe.d/tipc.conf
cp /etc/audisp/plugins.d/syslog.conf                                      backup/etc/audisp/plugins.d/syslog.conf
cp /etc/bluetooth/main.conf                                               backup/etc/bluetooth/main.conf
cp /etc/issue.net                                                         backup/etc/issue.net
cp /etc/mysql/mysql.conf.d/mysqld.cnf                                     backup/etc/mysql/mysql.conf.d/mysqld.cnf
cp /etc/init/control-alt-delete.conf                                      backup/etc/init/control-alt-delete.conf
cp /etc/init/avahi-daemon.override                                        backup/etc/init/avahi-daemon.override
cp /etc/init/cups.override                                                backup/etc/init/cups.override
cp /etc/init/modemmanager.override                                        backup/etc/init/modemmanager.override
cp /etc/init/control-alt-delete.override                                  backup/etc/init/control-alt-delete.override
cp /etc/init.d/ntp                                                        backup/etc/init.d/ntp
cp /etc/crontab                                                           backup/etc/crontab
cp /etc/securetty                                                         backup/etc/securetty
cp /etc/pam.d/su                                                          backup/etc/pam.d/su
cp /etc/pam.d/login                                                       backup/etc/pam.d/login
cp /etc/pam.d/common-password                                             backup/etc/pam.d/common-password
cp /etc/pam.d/common-account                                              backup/etc/pam.d/common-account
cp /etc/hosts.deny                                                        backup/etc/hosts.deny
cp /etc/denyhosts.conf                                                    backup/etc/denyhosts.conf
cp /etc/audit/audit.rules                                                 backup/etc/audit/audit.rules
cp /etc/audit/auditd.conf                                                 backup/etc/audit/auditd.conf
cp /etc/vsftpd.conf                                                       backup/etc/vsftpd.conf
cp /etc/csh.cshrc                                                         backup/etc/csh.cshrc
cp /etc/default/irqbalance                                                backup/etc/default/irqbalance
cp /etc/default/useradd                                                   backup/etc/default/useradd
cp /etc/default/whoopsie                                                  backup/etc/default/whoopsie
cp /etc/default/ufw                                                       backup/etc/default/ufw
cp /etc/default/grub                                                      backup/etc/default/grub
cp /etc/default/apport                                                    backup/etc/default/apport
cp /etc/sysctl.conf                                                       backup/etc/sysctl.conf
cp /etc/sudoers                                                           backup/etc/sudoers
cp /etc/skel/.bashrc                                                      backup/etc/skel/.bashrc
cp /etc/apache2/apache2.conf                                              backup/etc/apache2/apache2.conf
cp /etc/apache2/mods-enabled/mpm_event.conf                               backup/etc/apache2/mods-enabled/mpm_event.conf
cp /etc/apache2/mods-enabled/dir.conf                                     backup/etc/apache2/mods-enabled/dir.conf
cp /etc/apache2/mods-enabled/security2.conf                               backup/etc/apache2/mods-enabled/security2.conf
cp /etc/apache2/mods-enabled/reqtimeout.conf                              backup/etc/apache2/mods-enabled/reqtimeout.conf
cp /etc/apache2/mods-enabled/evasive.conf                                 backup/etc/apache2/mods-enabled/evasive.conf
cp /etc/apache2/mods-enabled/ssl.conf                                     backup/etc/apache2/mods-enabled/ssl.conf
cp /etc/apache2/conf-enabled/security.conf                                backup/etc/apache2/conf-enabled/security.conf
cp /etc/apache2/envvars                                                   backup/etc/apache2/envvars
cp /etc/apache2/sites-enabled/000-default.conf                            backup/etc/apache2/sites-enabled/000-default.conf
cp /etc/apache2/sites-enabled/default-ssl.conf                            backup/etc/apache2/sites-enabled/default-ssl.conf
cp /etc/ssh/sshd_config                                                   backup/etc/ssh/sshd_config
cp /etc/motd                                                              backup/etc/motd
cp /etc/security/limits.conf                                              backup/etc/security/limits.conf
cp /etc/security/access.conf                                              backup/etc/security/access.conf
cp /etc/security/pwquality.conf                                           backup/etc/security/pwquality.conf
cp /etc/bash.bashrc                                                       backup/etc/bash.bashrc
cp /etc/modsecurity/modsecurity.conf                                      backup/etc/modsecurity/modsecurity.conf
cp /etc/inittab                                                           backup/etc/inittab
cp /etc/ufw/before.rules                                                  backup/etc/ufw/before.rules
cp /etc/profile                                                           backup/etc/profile
cp /etc/ntp.conf                                                          backup/etc/ntp.conf
cp /etc/fstab                                                             backup/etc/fstab
cp /etc/samba/smb.conf                                                    backup/etc/samba/smb.conf
cp /etc/php/7.2/fpm/php.ini                                               backup/etc/php/7.2/fpm/php.ini
cp /etc/php/7.2/phpdbg/php.ini                                           backup/etc/php/7.2/phpdbg/php.ini
cp /etc/php/7.2/cli/php.ini                                               backup/etc/php/7.2/cli/php.ini
cp /etc/udev/rules.d/85-no-automount.rules                                backup/etc/udev/rules.d/85-no-automount.rules
cp /etc/login.defs                                                        backup/etc/login.defs
cp /etc/hosts.allow                                                       backup/etc/hosts.allow
cp /etc/issue                                                             backup/etc/issue
cp /etc/host.conf                                                         backup/etc/host.conf
cp /boot/grub/grub.cfg                                                    backup/boot/grub/grub.cfg
cp /lib/lsb/init-functions                                                backup/lib/lsb/init-functions
cp /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf                       backup/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
cp /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf	          backup/usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf	
cp /etc/nsswitch.conf                                                     backup/etc/nsswitch.conf
